### ISSUE TITLE
Workaround for slow SSD boot

### ISSUE THREAD

**Issue by bsv116** [DeskPi-Team/deskpi#7] opened 2020-12-07 22:56 UTC
There is a problem with SSD boot as the bridge chip from JMicron that is used in DeskPi is not UAS compatible. As a workaround, the section below can be added to the instruction "How to boot from USB SSD/HDD?". Further details and explanations can be found at [https://www.raspberrypi.org/forums/viewtopic.php?t=245931](https://www.raspberrypi.org/forums/viewtopic.php?t=245931)

**Disable UAS protocol for the JMicron chip**
`sudo nano /boot/cmdline.txt`
Insert `usb-storage.quirks=152d:0562:u ` first on the first line. Please note the trailing space.
Save and exit with ctrl+s ctrl+x

**Comment by Mister-42** [comment] 2020-12-08 08:56
Duplicate of #1

**Comment by yoyojacky** [comment] 2020-12-23 03:11
Please refer to :https://youtu.be/wUHZb9E_WDQ

**Closed by yoyojacky** 2020-12-23 03:11 UTC
